# @docs https://docs.gitlab.com/ee/ci/yaml

image: node:14 # current lts

variables:
  TERM: xterm-256color

before_script:
  - npm install

stages:
  - test
  - build

typescript:
  stage: test
  script:
    - npm run typecheck

prettier:
  stage: test
  script:
    - npm run prettycheck

lint:
  stage: test
  script:
    - npm run lint

jest:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week


release:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    IMAGE_DEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination
      $IMAGE_DEST
  only:
    - master
